name: Publish (web-only)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GODOT_VERSION: 4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # NOTE: Native embed files (godot_embed.example.mm / Swift) removed – pure Web export.
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com
      - name: Download Godot (headless + templates)
        run: |
          set -e
          BASE="https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}-stable"
          BIN="Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip"
          TPL="Godot_v${GODOT_VERSION}-stable_export_templates.tpz"
          mkdir -p godot-dl
          curl -L --fail "$BASE/$BIN" -o godot-dl/$BIN
          curl -L --fail "$BASE/$TPL" -o godot-dl/$TPL
          unzip -q godot-dl/$BIN -d godot-dl/bin
          unzip -q godot-dl/$TPL -d godot-dl/tpl
          mkdir -p ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          cp godot-dl/tpl/templates/* ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable/ || true
          chmod +x godot-dl/bin/Godot_v${GODOT_VERSION}-stable_linux.x86_64
      - name: Export Web
        run: |
          set -e
          test -f godot-project/project.godot
          mkdir -p web-export
          (cd godot-project && ../godot-dl/bin/Godot_v${GODOT_VERSION}-stable_linux.x86_64 --headless --export-release "Web" ../web-export/index.html)
          test -f web-export/index.html
      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build
      - name: Pack (dry-run)
        run: npm pack --dry-run
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
